services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    # Memuat file environment
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge